update deployment.yml 27

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -43,7 +43,7 @@ jobs:
       - name: 📡 Install lftp
         run: sudo apt-get update && sudo apt-get install -y lftp
 
-      - name: 🚀 Connect to FTP & Delete Files
+      - name: 🚀 Connect to FTP & Delete vendor
         env:
           FTP_HOST: ${{ secrets.FTP_HOST }}
           FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
@@ -53,10 +53,27 @@ jobs:
           set ssl:verify-certificate no
           open -u '$FTP_USERNAME','$FTP_PASSWORD' '$FTP_HOST'
           set ftp:sync-mode off
-          set cmd:parallel 200
+          set cmd:parallel 500
           set net:timeout 10
           set net:max-retries 2
           rm -rf /domains/firebrick-octopus-777457.hostingersite.com/laravel/vendor || echo 'vendor folder not found, skipping...'
+          bye
+          "
+
+      - name: 🚀 Connect to FTP & Delete Laravel_temp
+        env:
+          FTP_HOST: ${{ secrets.FTP_HOST }}
+          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
+          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
+        run: |
+          lftp -c "
+          set ssl:verify-certificate no
+          open -u '$FTP_USERNAME','$FTP_PASSWORD' '$FTP_HOST'
+          set ftp:sync-mode off
+          set cmd:parallel 500
+          set net:timeout 10
+          set net:max-retries 2
+          rm -rf /domains/firebrick-octopus-777457.hostingersite.com/laravel/laravel_temp || echo 'vendor folder not found, skipping...'
           bye
           "
 
@@ -67,7 +84,7 @@ jobs:
           user: ${{ secrets.FTP_USERNAME }}
           password: ${{ secrets.FTP_PASSWORD }}
           remoteFiles: "composer.json;composer.lock;artisan"
-          remoteDirectories: ";vendor;app;bootstrap;config;database;public;resources;routes;storage;laravel_temp"
+          remoteDirectories: "app;bootstrap;config;database;public;resources;routes;storage"
           workingDir: "/domains/firebrick-octopus-777457.hostingersite.com/laravel"
           ignoreSSL: "1"
 
